import { useEffect, useRef, useState } from "react";
import {
  AnimatePresence,
  Reorder,
  motion,
  useDragControls,
} from "motion/react";
import { Check, GripVertical, Plus, Trash2, X } from "lucide-react";
import type { TaskStream } from "../types";
import { useKeyboardInset } from "../hooks/useKeyboardInset";

// ─────────────────────────────────────────────────────────────────────────────
// Settings sheet: edit the user's name, plus manage streams (rename, reorder by
// drag, add, delete).
//
// The rows are kept in LOCAL state (`rows`) for the duration the sheet is open,
// seeded from props when it opens. Every edit updates that local state AND
// mirrors the change to the store via the callbacks, so the sheet stays smooth
// (no round-trip flicker while dragging) while the store remains the source of
// truth on next open. Ids are generated by the store's `onAdd` and returned, so
// local rows and persisted streams always share the same id.
// ─────────────────────────────────────────────────────────────────────────────

interface Row {
  id: string;
  name: string;
}

interface StreamManagerModalProps {
  open: boolean;
  userName: string;
  streams: TaskStream[];
  /** Task count per stream id, for the delete confirmation. */
  taskCounts: Record<string, number>;
  onClose: () => void;
  onRenameUser: (name: string) => void;
  onAdd: (name?: string) => string;
  onRename: (id: string, name: string) => void;
  onDelete: (id: string) => void;
  onReorder: (orderedIds: string[]) => void;
}

export function StreamManagerModal({
  open,
  userName,
  streams,
  taskCounts,
  onClose,
  onRenameUser,
  onAdd,
  onRename,
  onDelete,
  onReorder,
}: StreamManagerModalProps) {
  const keyboardInset = useKeyboardInset();
  const [rows, setRows] = useState<Row[]>([]);
  const [nameDraft, setNameDraft] = useState("");
  const [confirmId, setConfirmId] = useState<string | null>(null);
  const focusId = useRef<string | null>(null);

  // Seed only when the sheet opens — not on every prop change — so our own
  // in-session edits aren't clobbered by the store echoing them back.
  useEffect(() => {
    if (open) {
      setRows(streams.map((s) => ({ id: s.id, name: s.name })));
      setNameDraft(userName);
      setConfirmId(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  function commitUserName() {
    if (nameDraft.trim()) onRenameUser(nameDraft);
    else setNameDraft(userName); // reject empty — restore the stored name
  }

  function handleReorder(next: Row[]) {
    setRows(next);
    onReorder(next.map((r) => r.id));
  }

  function handleRename(id: string, name: string) {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, name } : r)));
  }

  function commitRename(id: string) {
    const row = rows.find((r) => r.id === id);
    if (row) onRename(id, row.name);
  }

  function handleDelete(id: string) {
    setRows((prev) => prev.filter((r) => r.id !== id));
    setConfirmId(null);
    onDelete(id);
  }

  function handleAdd() {
    const id = onAdd("New stream");
    focusId.current = id;
    setRows((prev) => [...prev, { id, name: "New stream" }]);
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          style={{
            background: "rgba(10,9,8,0.6)",
            paddingBottom: keyboardInset,
            transition: "padding-bottom 0.2s ease",
          }}
        >
          <motion.div
            className="border-border-warm max-h-full w-full max-w-[420px] overflow-y-auto rounded-t-3xl border bg-[#211e1b] p-5 sm:rounded-3xl"
            initial={{ y: 40, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 40, opacity: 0 }}
            transition={{ type: "spring", stiffness: 320, damping: 30 }}
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-cream font-serif text-[18px] font-medium">
                Settings
              </h2>
              <button onClick={onClose} aria-label="Close" className="text-muted">
                <X size={20} />
              </button>
            </div>

            {/* Name section */}
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Your name
            </label>
            <input
              value={nameDraft}
              maxLength={40}
              onChange={(e) => setNameDraft(e.target.value)}
              onBlur={commitUserName}
              onKeyDown={(e) => {
                if (e.key === "Enter") e.currentTarget.blur();
              }}
              // 16px avoids iOS Safari's auto-zoom on input focus.
              className="border-border-warm bg-bg text-cream placeholder:text-muted-soft focus:border-clay/60 w-full rounded-xl border px-3.5 py-2.5 text-[16px] outline-none"
              placeholder="Your name"
            />

            {/* Divider between sections */}
            <div className="border-border-warm my-5 border-t" />

            {/* Streams section */}
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Streams
            </label>
            <p className="text-muted-soft mb-3 text-[12px] leading-[1.5]">
              Drag to reorder · tap a name to rename. Deleting a stream also
              deletes every task inside it.
            </p>

            <Reorder.Group
              as="div"
              axis="y"
              values={rows}
              onReorder={handleReorder}
              className="max-h-[46vh] space-y-2 overflow-y-auto overscroll-contain"
            >
              {rows.map((row) => (
                <StreamRow
                  key={row.id}
                  row={row}
                  count={taskCounts[row.id] ?? 0}
                  canDelete={rows.length > 1}
                  confirming={confirmId === row.id}
                  autoFocus={focusId.current === row.id}
                  onRename={handleRename}
                  onCommit={commitRename}
                  onRequestDelete={() => setConfirmId(row.id)}
                  onCancelDelete={() => setConfirmId(null)}
                  onConfirmDelete={() => handleDelete(row.id)}
                />
              ))}
            </Reorder.Group>

            <button
              onClick={handleAdd}
              className="text-clay hover:text-cream-soft mt-4 flex w-full items-center justify-center gap-1.5 rounded-xl border border-dashed border-[#4E473C] py-2.5 text-[13px] transition-colors"
            >
              <Plus size={16} /> New stream
            </button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

interface StreamRowProps {
  row: Row;
  count: number;
  canDelete: boolean;
  confirming: boolean;
  autoFocus: boolean;
  onRename: (id: string, name: string) => void;
  onCommit: (id: string) => void;
  onRequestDelete: () => void;
  onCancelDelete: () => void;
  onConfirmDelete: () => void;
}

function StreamRow({
  row,
  count,
  canDelete,
  confirming,
  autoFocus,
  onRename,
  onCommit,
  onRequestDelete,
  onCancelDelete,
  onConfirmDelete,
}: StreamRowProps) {
  // Per-row drag controls so ONLY the grip handle starts a drag — dragging from
  // the text input would otherwise fight with selecting/editing the name.
  const controls = useDragControls();
  const inputRef = useRef<HTMLInputElement>(null);
  // Raise the row being dragged above all others (Reorder doesn't do this on its
  // own, so otherwise a neighbour paints over the one you're moving).
  const [dragging, setDragging] = useState(false);

  useEffect(() => {
    if (autoFocus && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [autoFocus]);

  return (
    <Reorder.Item
      as="div"
      value={row}
      dragListener={false}
      dragControls={controls}
      onDragStart={() => setDragging(true)}
      onDragEnd={() => setDragging(false)}
      style={{
        position: "relative",
        zIndex: dragging ? 50 : 0,
        boxShadow: dragging
          ? "0 12px 28px -10px rgba(20,14,8,0.7)"
          : "none",
      }}
      className="border-border-warm flex items-center gap-2 rounded-xl border bg-bg px-2.5 py-2"
    >
      <button
        aria-label="Drag to reorder"
        onPointerDown={(e) => controls.start(e)}
        className="text-muted hover:text-cream-soft -ml-1 shrink-0 cursor-grab touch-none p-1.5 transition-colors active:cursor-grabbing"
      >
        <GripVertical size={18} />
      </button>

      <input
        ref={inputRef}
        value={row.name}
        onChange={(e) => onRename(row.id, e.target.value)}
        onBlur={() => onCommit(row.id)}
        onKeyDown={(e) => {
          if (e.key === "Enter") e.currentTarget.blur();
        }}
        // 16px avoids iOS Safari's auto-zoom on input focus.
        className="text-cream min-w-0 flex-1 bg-transparent text-[16px] outline-none"
      />

      {confirming ? (
        <div className="flex shrink-0 items-center gap-1">
          <span className="whitespace-nowrap text-[11px] text-[#C0584A]">
            Delete{count > 0 ? ` · ${count} task${count === 1 ? "" : "s"}` : ""}?
          </span>
          <button
            onClick={onConfirmDelete}
            aria-label="Confirm delete"
            className="rounded-full bg-[#5A2C24] p-1.5 text-[#E9C7C0] transition-transform active:scale-90"
          >
            <Check size={15} />
          </button>
          <button
            onClick={onCancelDelete}
            aria-label="Cancel delete"
            className="text-muted p-1.5"
          >
            <X size={15} />
          </button>
        </div>
      ) : (
        <div className="flex shrink-0 items-center gap-1">
          {count > 0 && (
            <span className="text-muted-soft text-[11px] tabular-nums">
              {count}
            </span>
          )}
          <button
            onClick={onRequestDelete}
            disabled={!canDelete}
            aria-label="Delete stream"
            className="text-muted -mr-1 p-1.5 transition-colors enabled:hover:text-[#C0584A] disabled:opacity-30"
            title={canDelete ? "Delete stream" : "Keep at least one stream"}
          >
            <Trash2 size={17} />
          </button>
        </div>
      )}
    </Reorder.Item>
  );
}
