import { useEffect, useRef, useState } from "react";
import {
  AnimatePresence,
  Reorder,
  motion,
  useDragControls,
} from "motion/react";
import {
  Check,
  Compass,
  Download,
  GripVertical,
  Plus,
  Repeat,
  Trash2,
  Upload,
  X,
} from "lucide-react";
import type { SawaData, Task, TaskStream } from "../types";
import { useKeyboardInset } from "../hooks/useKeyboardInset";
import { CARD_THEMES, DEFAULT_CARD_THEME_ID } from "../lib/cardThemes";
import { downloadBackup, parseBackup } from "../lib/backup";

// ─────────────────────────────────────────────────────────────────────────────
// Settings sheet: edit the user's name, plus manage streams (rename, reorder by
// drag, add, delete).
//
// The rows are kept in LOCAL state (`rows`) for the duration the sheet is open,
// seeded from props when it opens. Every edit updates that local state AND
// mirrors the change to the store via the callbacks, so the sheet stays smooth
// (no round-trip flicker while dragging) while the store remains the source of
// truth on next open. Ids are generated by the store's `onAdd` and returned, so
// local rows and persisted streams always share the same id.
// ─────────────────────────────────────────────────────────────────────────────

interface Row {
  id: string;
  name: string;
}

interface StreamManagerModalProps {
  open: boolean;
  userName: string;
  streams: TaskStream[];
  /** Task count per stream id, for the delete confirmation. */
  taskCounts: Record<string, number>;
  onClose: () => void;
  onRenameUser: (name: string) => void;
  onAdd: (name?: string) => string;
  onRename: (id: string, name: string) => void;
  onDelete: (id: string) => void;
  onReorder: (orderedIds: string[]) => void;
  /** Recurring templates, to view and stop. */
  templates: Task[];
  onStopRepeat: (id: string) => void;
  /** Selected card theme id + setter. */
  cardThemeId?: string;
  onSelectTheme: (id: string) => void;
  /** Whole dataset, for exporting a backup file. */
  data: SawaData;
  /** Restore a parsed backup, replacing all current data. */
  onImport: (data: SawaData) => void;
  /** Replay the first-run walkthrough. */
  onReplayTour: () => void;
}

export function StreamManagerModal({
  open,
  userName,
  streams,
  taskCounts,
  onClose,
  onRenameUser,
  onAdd,
  onRename,
  onDelete,
  onReorder,
  templates,
  onStopRepeat,
  cardThemeId,
  onSelectTheme,
  data,
  onImport,
  onReplayTour,
}: StreamManagerModalProps) {
  const selectedTheme = cardThemeId ?? DEFAULT_CARD_THEME_ID;
  const keyboardInset = useKeyboardInset();
  const [rows, setRows] = useState<Row[]>([]);
  const [nameDraft, setNameDraft] = useState("");
  const [confirmId, setConfirmId] = useState<string | null>(null);
  const focusId = useRef<string | null>(null);
  // Backup import: a hidden file input, plus a transient status line.
  const fileRef = useRef<HTMLInputElement>(null);
  const [backupNote, setBackupNote] = useState<{
    kind: "ok" | "error";
    text: string;
  } | null>(null);

  // Seed only when the sheet opens — not on every prop change — so our own
  // in-session edits aren't clobbered by the store echoing them back.
  useEffect(() => {
    if (open) {
      setRows(streams.map((s) => ({ id: s.id, name: s.name })));
      setNameDraft(userName);
      setConfirmId(null);
      setBackupNote(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  function commitUserName() {
    if (nameDraft.trim()) onRenameUser(nameDraft);
    else setNameDraft(userName); // reject empty — restore the stored name
  }

  function handleReorder(next: Row[]) {
    setRows(next);
    onReorder(next.map((r) => r.id));
  }

  function handleRename(id: string, name: string) {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, name } : r)));
  }

  function commitRename(id: string) {
    const row = rows.find((r) => r.id === id);
    if (row) onRename(id, row.name);
  }

  function handleDelete(id: string) {
    setRows((prev) => prev.filter((r) => r.id !== id));
    setConfirmId(null);
    onDelete(id);
  }

  function handleAdd() {
    const id = onAdd("New stream");
    focusId.current = id;
    setRows((prev) => [...prev, { id, name: "New stream" }]);
  }

  function handleExport() {
    downloadBackup(data);
    setBackupNote({ kind: "ok", text: "Backup downloaded." });
  }

  async function handleImportFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = ""; // allow re-selecting the same file later
    if (!file) return;
    try {
      const restored = parseBackup(await file.text());
      onImport(restored);
      setBackupNote({
        kind: "ok",
        text: `Restored ${restored.tasks.length} task${
          restored.tasks.length === 1 ? "" : "s"
        }.`,
      });
    } catch (err) {
      setBackupNote({
        kind: "error",
        text: err instanceof Error ? err.message : "Couldn't read that file.",
      });
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          style={{
            background: "rgba(10,9,8,0.6)",
            paddingBottom: keyboardInset,
            transition: "padding-bottom 0.2s ease",
          }}
        >
          <motion.div
            className="border-border-warm max-h-full w-full max-w-[420px] overflow-y-auto rounded-t-3xl border bg-[#211e1b] p-5 sm:rounded-3xl"
            initial={{ y: 40, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 40, opacity: 0 }}
            transition={{ type: "spring", stiffness: 320, damping: 30 }}
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-cream font-serif text-[18px] font-medium">
                Settings
              </h2>
              <button onClick={onClose} aria-label="Close" className="text-muted">
                <X size={20} />
              </button>
            </div>

            {/* Name section */}
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Your name
            </label>
            <input
              value={nameDraft}
              maxLength={40}
              onChange={(e) => setNameDraft(e.target.value)}
              onBlur={commitUserName}
              onKeyDown={(e) => {
                if (e.key === "Enter") e.currentTarget.blur();
              }}
              // 16px avoids iOS Safari's auto-zoom on input focus.
              className="border-border-warm bg-bg text-cream placeholder:text-muted-soft focus:border-clay/60 w-full rounded-xl border px-3.5 py-2.5 text-[16px] outline-none"
              placeholder="Your name"
            />

            {/* Divider between sections */}
            <div className="border-border-warm my-5 border-t" />

            {/* Streams section */}
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Streams
            </label>
            <p className="text-muted-soft mb-3 text-[12px] leading-[1.5]">
              Drag to reorder · tap a name to rename. Deleting a stream also
              deletes every task inside it.
            </p>

            <Reorder.Group
              as="div"
              axis="y"
              values={rows}
              onReorder={handleReorder}
              className="max-h-[46vh] space-y-2 overflow-y-auto overscroll-contain"
            >
              {rows.map((row) => (
                <StreamRow
                  key={row.id}
                  row={row}
                  count={taskCounts[row.id] ?? 0}
                  canDelete={rows.length > 1}
                  confirming={confirmId === row.id}
                  autoFocus={focusId.current === row.id}
                  onRename={handleRename}
                  onCommit={commitRename}
                  onRequestDelete={() => setConfirmId(row.id)}
                  onCancelDelete={() => setConfirmId(null)}
                  onConfirmDelete={() => handleDelete(row.id)}
                />
              ))}
            </Reorder.Group>

            <button
              onClick={handleAdd}
              className="text-clay hover:text-cream-soft mt-4 flex w-full items-center justify-center gap-1.5 rounded-xl border border-dashed border-[#4E473C] py-2.5 text-[13px] transition-colors"
            >
              <Plus size={16} /> New stream
            </button>

            {/* Card themes */}
            <div className="border-border-warm my-5 border-t" />
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Card theme
            </label>
            <p className="text-muted-soft mb-3 text-[12px] leading-[1.5]">
              The paper your task cards are printed on.
            </p>
            <div className="grid grid-cols-3 gap-2">
              {CARD_THEMES.map((t) => {
                const on = selectedTheme === t.id;
                return (
                  <button
                    key={t.id}
                    onClick={() => onSelectTheme(t.id)}
                    aria-pressed={on}
                    className="flex flex-col items-stretch gap-1.5 rounded-xl p-1 transition-transform active:scale-[0.97]"
                    style={{
                      background: on ? "#2c2a22" : "transparent",
                      outline: on ? "1.5px solid #C96442" : "1.5px solid transparent",
                    }}
                  >
                    {/* A simplified mock of a real card, so the ink/paper contrast
                        of each theme is visible at a glance. */}
                    <span
                      className="relative block h-[54px] w-full overflow-hidden rounded-lg"
                      style={{ background: t.bg, border: `1px solid ${t.border}` }}
                    >
                      <span
                        className="absolute bottom-0 left-0 top-0 w-[3px]"
                        style={{ background: "#C96442" }}
                      />
                      {/* 沢 watermark */}
                      <span
                        className="absolute -bottom-2 right-0 select-none font-serif leading-none"
                        style={{ fontSize: 34, color: t.watermark }}
                      >
                        沢
                      </span>
                      {/* title + two description lines, echoing a real card */}
                      <span className="absolute left-[11px] right-[9px] top-[11px] flex flex-col">
                        <span
                          className="h-[6px] w-[70%] rounded-full"
                          style={{ background: t.ink, opacity: 0.9 }}
                        />
                        <span
                          className="mt-[7px] h-[3px] w-[60%] rounded-full"
                          style={{ background: t.inkSoft, opacity: 0.8 }}
                        />
                        <span
                          className="mt-[4px] h-[3px] w-[45%] rounded-full"
                          style={{ background: t.inkSoft, opacity: 0.65 }}
                        />
                      </span>
                      {/* a chip */}
                      <span
                        className="absolute bottom-[9px] left-[11px] h-[8px] w-[18px] rounded-full"
                        style={{ background: t.chipBg }}
                      />
                    </span>
                    <span className="flex items-center justify-center gap-1 text-[11px] text-cream-soft">
                      {on && <Check size={11} className="text-clay" />}
                      {t.name}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Repeating tasks */}
            {templates.length > 0 && (
              <>
                <div className="border-border-warm my-5 border-t" />
                <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
                  Repeating
                </label>
                <p className="text-muted-soft mb-3 text-[12px] leading-[1.5]">
                  These reappear as a fresh card every day. Stop one to end its
                  daily repeat.
                </p>
                <div className="space-y-2">
                  {templates.map((t) => (
                    <div
                      key={t.id}
                      className="border-border-warm bg-bg flex items-center gap-2 rounded-xl border px-3 py-2"
                    >
                      <Repeat size={15} className="text-gold shrink-0" />
                      <span className="text-cream-soft min-w-0 flex-1 truncate text-[14px]">
                        {t.title}
                      </span>
                      <button
                        onClick={() => onStopRepeat(t.id)}
                        className="text-muted shrink-0 rounded-full px-2 py-1 text-[12px] transition-colors hover:text-[#C0584A]"
                      >
                        Stop
                      </button>
                    </div>
                  ))}
                </div>
              </>
            )}

            {/* Backup: export / import the whole dataset as a JSON file */}
            <div className="border-border-warm my-5 border-t" />
            <label className="text-muted-soft mb-1.5 block text-[11px] font-medium uppercase tracking-[1px]">
              Backup
            </label>
            <p className="text-muted-soft mb-3 text-[12px] leading-[1.5]">
              Save all your tasks and streams to a file, or restore from one.
              Importing replaces everything currently here.
            </p>
            <div className="flex gap-2">
              <button
                onClick={handleExport}
                className="border-border-warm text-cream-soft hover:border-clay/60 flex flex-1 items-center justify-center gap-2 rounded-xl border py-2.5 text-[13px] transition-colors"
              >
                <Download size={15} /> Export
              </button>
              <button
                onClick={() => fileRef.current?.click()}
                className="border-border-warm text-cream-soft hover:border-clay/60 flex flex-1 items-center justify-center gap-2 rounded-xl border py-2.5 text-[13px] transition-colors"
              >
                <Upload size={15} /> Import
              </button>
              <input
                ref={fileRef}
                type="file"
                accept="application/json,.json"
                className="hidden"
                onChange={handleImportFile}
              />
            </div>
            {backupNote && (
              <p
                className="mt-2 text-[12px]"
                style={{ color: backupNote.kind === "ok" ? "#8FA37A" : "#C0584A" }}
              >
                {backupNote.text}
              </p>
            )}

            {/* Divider + walkthrough replay */}
            <div className="border-border-warm my-5 border-t" />
            <button
              onClick={() => {
                onClose();
                onReplayTour();
              }}
              className="text-muted hover:text-cream-soft flex w-full items-center justify-between rounded-xl py-1 text-[13px] transition-colors"
            >
              <span className="flex items-center gap-2">
                <Compass size={16} /> Show walkthrough
              </span>
              <span className="text-muted-soft text-[11px]">Replay the intro tour</span>
            </button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

interface StreamRowProps {
  row: Row;
  count: number;
  canDelete: boolean;
  confirming: boolean;
  autoFocus: boolean;
  onRename: (id: string, name: string) => void;
  onCommit: (id: string) => void;
  onRequestDelete: () => void;
  onCancelDelete: () => void;
  onConfirmDelete: () => void;
}

function StreamRow({
  row,
  count,
  canDelete,
  confirming,
  autoFocus,
  onRename,
  onCommit,
  onRequestDelete,
  onCancelDelete,
  onConfirmDelete,
}: StreamRowProps) {
  // Per-row drag controls so ONLY the grip handle starts a drag — dragging from
  // the text input would otherwise fight with selecting/editing the name.
  const controls = useDragControls();
  const inputRef = useRef<HTMLInputElement>(null);
  // Raise the row being dragged above all others (Reorder doesn't do this on its
  // own, so otherwise a neighbour paints over the one you're moving).
  const [dragging, setDragging] = useState(false);

  useEffect(() => {
    if (autoFocus && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [autoFocus]);

  return (
    <Reorder.Item
      as="div"
      value={row}
      dragListener={false}
      dragControls={controls}
      onDragStart={() => setDragging(true)}
      onDragEnd={() => setDragging(false)}
      style={{
        position: "relative",
        zIndex: dragging ? 50 : 0,
        boxShadow: dragging
          ? "0 12px 28px -10px rgba(20,14,8,0.7)"
          : "none",
      }}
      className="border-border-warm flex items-center gap-2 rounded-xl border bg-bg px-2.5 py-2"
    >
      <button
        aria-label="Drag to reorder"
        onPointerDown={(e) => controls.start(e)}
        className="text-muted hover:text-cream-soft -ml-1 shrink-0 cursor-grab touch-none p-1.5 transition-colors active:cursor-grabbing"
      >
        <GripVertical size={18} />
      </button>

      <input
        ref={inputRef}
        value={row.name}
        onChange={(e) => onRename(row.id, e.target.value)}
        onBlur={() => onCommit(row.id)}
        onKeyDown={(e) => {
          if (e.key === "Enter") e.currentTarget.blur();
        }}
        // 16px avoids iOS Safari's auto-zoom on input focus.
        className="text-cream min-w-0 flex-1 bg-transparent text-[16px] outline-none"
      />

      {confirming ? (
        <div className="flex shrink-0 items-center gap-1">
          <span className="whitespace-nowrap text-[11px] text-[#C0584A]">
            Delete{count > 0 ? ` · ${count} task${count === 1 ? "" : "s"}` : ""}?
          </span>
          <button
            onClick={onConfirmDelete}
            aria-label="Confirm delete"
            className="rounded-full bg-[#5A2C24] p-1.5 text-[#E9C7C0] transition-transform active:scale-90"
          >
            <Check size={15} />
          </button>
          <button
            onClick={onCancelDelete}
            aria-label="Cancel delete"
            className="text-muted p-1.5"
          >
            <X size={15} />
          </button>
        </div>
      ) : (
        <div className="flex shrink-0 items-center gap-1">
          {count > 0 && (
            <span className="text-muted-soft text-[11px] tabular-nums">
              {count}
            </span>
          )}
          <button
            onClick={onRequestDelete}
            disabled={!canDelete}
            aria-label="Delete stream"
            className="text-muted -mr-1 p-1.5 transition-colors enabled:hover:text-[#C0584A] disabled:opacity-30"
            title={canDelete ? "Delete stream" : "Keep at least one stream"}
          >
            <Trash2 size={17} />
          </button>
        </div>
      )}
    </Reorder.Item>
  );
}
